services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app

  frontend:
    build: 
      context: ./frontend
    ports:
      - "8501:8501"